### ISSUE TITLE
Whitepaper Link

### ISSUE THREAD

**Issue by cjenken** [Avalanche-io/c4#32]
Should it go to here?: 
https://www.etcentric.org/wp-content/uploads/2015/09/C4-ID-ETC-Whitepaper.pdf

**Comment by mrjoshuak** [comment]
No that is the one that keeps floating around that is wrong.  It uses the old character-set that sorts differently then the digest form. The correct character-set is:

```go
"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
```

**Comment by cjenken** [comment]
Ah.  OK.  Thanks :)

**Comment by mrjoshuak** [comment]
I fixed the link in the Readme.md. Added here for reference:

Current revision: http://www.cccc.io/c4id-whitepaper-u2.pdf
